
version: '3'

services:
  autotrader:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_SECRET_KEY=${ALPACA_SECRET_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - IB_API_KEY=${IB_API_KEY}
      - IB_SECRET_KEY=${IB_SECRET_KEY}
